version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - app_net

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
